role: separator
twig_name: Separator
examples:
  - id: horizontal
    title: Horizontal
    section: Orientation
    props:
      orientation: "horizontal"
    slot_text: ''
  - id: vertical
    title: Vertical
    section: Orientation
    props:
      orientation: "vertical"
    slot_text: ''
