role: skeleton
twig_name: Skeleton
examples:
  - id: line
    title: Text line
    section: Examples
    props: {}
    slot_text: ''
  - id: block
    title: Block
    section: Examples
    props:
      variant: "block"
    slot_text: ''
